import './assets/images/favicon.png';
import './assets/styles/index.css';
import './assets/styles/footer.css';
import './assets/styles/greeting.css';
import './assets/styles/calculator.css';
import './assets/styles/convertor.css';
import './utils/changeTheme';
import './utils/calculator';
import './utils/lang';
